import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["400", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={inter.className}>
      <head />
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
